#include <QString>
#include <QtTest>
#include <sstream>

#include "date.hh"

// Needed to make the macros of Qt tests to work with Weekday enum
// (not so important issue)
Q_DECLARE_METATYPE(Date::Weekday);

class Unittest : public QObject
{
    Q_OBJECT

public:
    Unittest();

private Q_SLOTS:
    void dateCreation();

    void FebruaryLegalDays();
    void FebruaryIllegalDays();

    void setMonth();

    void lastDaysOfMonth();
    void lastDaysOfMonth_data();

    void weekday();
    void weekday_data();

    void print();
};

Unittest::Unittest()
{
}

void Unittest::dateCreation()
{
    // Simple testi, which test creation of a date
    Date d(1, 2, 2014);
    QCOMPARE(d.giveDay(), 1u); // 1u needed since the return value of giveDay is unsigned int
    QCOMPARE(d.giveMonth(), 2u);
    QCOMPARE(d.giveYear(), 2014u);
}

void Unittest::print()
{
    // Creating and printing the date into string, checking if ok
    Date d(4, 5, 2000);
    std::ostringstream printStream;
    d.print(&printStream);
    QCOMPARE(printStream.str(), std::string("4.5.2000"));

    // Testataan tulostus tyhjällä osoittimella
    d.print(nullptr);
}

void Unittest::FebruaryLegalDays()
{
    // Testing all days of February in a loop, checking if ok

    for (unsigned int day = 1; day <= 28; ++day)
    {
        Date d(1, 2, 2014);

        d.setDay(day);
        QCOMPARE(d.giveDay(), day);
//            try
//            {
//                d.setDay(day);
//                QCOMPARE(d.giveDay(), day);
//            }
//            catch (...)
//            {
//                QFAIL("Exception from the legal operation");
//            }
    }
}

void Unittest::FebruaryIllegalDays()
{
    // Testing "February days" 29-31, checking if not ok

    for (unsigned int day = 29; day <= 31; ++day)
    {
        Date d(1, 2, 2014);

        QVERIFY_EXCEPTION_THROWN(d.setDay(day), BadDate);
    }
}

void Unittest::setMonth()
{
    // Testing the first days of all months in a loop

    Date d(1, 1, 2014);
    for (unsigned int month = 1; month <= 12; ++month)
    {
        d.setMonth(month);
        QCOMPARE(d.giveDay(), 1u);
        QCOMPARE(d.giveMonth(), month);
        QCOMPARE(d.giveYear(), 2014u);
    }
}

void Unittest::lastDaysOfMonth()
{
    // Creting date for the last day of each month
    QFETCH(unsigned int, month);
    QFETCH(unsigned int, length);

    // Creating date, moving to the next day, checking the change of a month
    Date d(length, month, 2014);
    d.step(1);
    QCOMPARE(d.giveMonth(), month+1);
}

void Unittest::lastDaysOfMonth_data()
{
    // This method defines the test matrix of the month test and generated desired test cases there

    // Defining the columns of the test matrix (types and names)
    QTest::addColumn<unsigned int>("month");
    QTest::addColumn<unsigned int>("length");

    // Generates the test cases of the test matrix, 31u etc. are needed since type is unsigned
    QTest::newRow("January") << 1u << 31u;
    QTest::newRow("February") << 2u << 28u;
    QTest::newRow("March") << 3u << 31u;
    QTest::newRow("April") << 4u << 30u;
    QTest::newRow("May") << 5u << 31u;
    QTest::newRow("June") << 6u << 30u;
    QTest::newRow("July") << 7u << 31u;
    QTest::newRow("August") << 8u << 31u;
    QTest::newRow("September") << 9u << 30u;
    QTest::newRow("October") << 10u << 311u;
    QTest::newRow("November") << 11u << 30u;
    QTest::newRow("December") << 12u << 31u;
}

void Unittest::weekday()
{
    // This method tests a row of the test matrix generated by the method weekday_data.
    // It is called automatically for each row of the matrix

    // Fetching data from the matrix, variables are created automatically
    QFETCH(unsigned int, day);
    QFETCH(unsigned int, month);
    QFETCH(unsigned int, year);
    QFETCH(Date::Weekday, weekday);

    // Performing the test
    Date d(day, month, year);
    QVERIFY2(d.giveWeekday() == weekday, "Wrong weekday");
}

void Unittest::weekday_data()
{
    // This method defines the test matrix for the weekday test and generates the desired test cases there

    // Defining columns for the test matrix (types and names)
    QTest::addColumn<unsigned int>("day");
    QTest::addColumn<unsigned int>("month");
    QTest::addColumn<unsigned int>("year");
    QTest::addColumn<Date::Weekday>("weekday");

    // Generating test cases for the test matrix, 3u etc. are needed since the type is unsigned
    QTest::newRow("today")      << 3u  << 2u  << 2014u << Date::MONDAY;
    QTest::newRow("last Christmas") << 24u << 12u << 2013u << Date::TUESDAY;
    QTest::newRow("next May Day")  << 1u  << 5u  << 2014u << Date::THURSDAY;
    QTest::newRow("end of the year")<< 31u << 12u << 2013u << Date::TUESDAY;
    QTest::newRow("new year")  << 1u  << 1u  << 2014u << Date::WEDNESDAY;
}


QTEST_APPLESS_MAIN(Unittest)

#include "tst_unittest.moc"
